### ISSUE TITLE
Command "python setup.py egg_info" failed with error code 1

### ISSUE THREAD

**Issue by zulhfreelancer** [shriar/Insta-post#1]
Hi,

I'm getting this error when trying to run the `pip` command.

```
/tmp/Insta-post (master ✔) ᐅ pip install -U https://github.com/jacexh/pyautoit/archive/master.zip                                                               
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Collecting https://github.com/jacexh/pyautoit/archive/master.zip
  Downloading https://github.com/jacexh/pyautoit/archive/master.zip
     \ 675kB 7.4MB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/n_/gd4bz2y92l1834sjbsb6nhlr0000gn/T/pip-req-build-wAL7UZ/setup.py", line 8, in <module>
        import autoit
      File "autoit/__init__.py", line 6, in <module>
        from .autoit import options, properties, commands
      File "autoit/autoit.py", line 7, in <module>
        from ctypes.wintypes import *
      File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ctypes/wintypes.py", line 19, in <module>
        class VARIANT_BOOL(_SimpleCData):
    ValueError: _type_ 'v' not supported

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/n_/gd4bz2y92l1834sjbsb6nhlr0000gn/T/pip-req-build-wAL7UZ/

/tmp/Insta-post (master ✔) ᐅ pip3 install -U https://github.com/jacexh/pyautoit/archive/master.zip                                                              
Collecting https://github.com/jacexh/pyautoit/archive/master.zip
  Using cached https://github.com/jacexh/pyautoit/archive/master.zip
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/n_/gd4bz2y92l1834sjbsb6nhlr0000gn/T/pip-req-build-avp5qm85/setup.py", line 8, in <module>
        import autoit
      File "/private/var/folders/n_/gd4bz2y92l1834sjbsb6nhlr0000gn/T/pip-req-build-avp5qm85/autoit/__init__.py", line 6, in <module>
        from .autoit import options, properties, commands
      File "/private/var/folders/n_/gd4bz2y92l1834sjbsb6nhlr0000gn/T/pip-req-build-avp5qm85/autoit/autoit.py", line 7, in <module>
        from ctypes.wintypes import *
      File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ctypes/wintypes.py", line 20, in <module>
        class VARIANT_BOOL(ctypes._SimpleCData):
    ValueError: _type_ 'v' not supported

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/n_/gd4bz2y92l1834sjbsb6nhlr0000gn/T/pip-req-build-avp5qm85/
```

Any idea how to fix it?

Thank you.

**Comment by ernestomehra** [comment]
May be use this:


pip install -U pyautoit

Or download the code in .zip unarchive it and run this command where setup.py lives. 

Python setup.py install
